language: cpp
dist: bionic
compiler:
- clang
os:
- linux
install:
- sudo apt-get install libboost1.71-dev libboost-log1.71-dev cmake build-essential
# For now, just build. We add tests later.
script:
- mkdir build && cd build && cmake .. && make

